#!/bin/zsh
file "$1" | grep -q "text"
if [ $? -ne 0 ]; then
  /usr/bin/open $1
else
  IDEA_EXECUTABLE=/Applications/IntelliJ\ IDEA.app/Contents/MacOS/idea
  if [[ $# -eq 2 ]]; then
    $IDEA_EXECUTABLE --line $2 $1
  else
    $IDEA_EXECUTABLE $1
  fi
fi
